import type { OutputLang, PracticeArea, Side } from "./types";

export const copy = {
  hi: {
    app: "CiteBench",
    tagline: "अधिवक्ताओं के लिए प्रैक्टिस असिस्टेंट · केस-लॉ रिसर्च",
    hero: "तथ्य लिखें। नज़ीर निकल आए।",
    kicker: "सुप्रीम कोर्ट · उच्च न्यायालय · भारतीय कानून",
    facts: "केस के तथ्य",
    factsHint:
      "जो हुआ, साफ लिखें — पक्षकार, तारीखें, दस्तावेज़, विवाद, और जो राहत चाहिए। हिंदी या अंग्रेज़ी, दोनों चलेंगे।",
    query: "खास कानूनी सवाल",
    queryHint: "जैसे — क्या अग्रिम ज़मानत बनती है? क्या रिट चलेगी?",
    court: "अदालत",
    area: "विषय",
    side: "पक्ष",
    memoLang: "मेमो की भाषा",
    research: "शोध शुरू करें",
    researching: "शोध चल रहा है…",
    newBrief: "नया ब्रीफ",
    history: "पिछले मेमो",
    samples: "नमूना ब्रीफ",
    how: "कैसे काम करता है",
    step1: "तथ्य लिखें या FIR/आदेश अपलोड करें",
    step2: "CiteBench SCI, eSCR, Indian Kanoon, LiveLaw, CaseMine पर खोजता है",
    step3: "मिलते-जुलते निर्णयों से मुद्दे, सिद्धांत और दलीलें बनती हैं",
    step4: "पूरा कानूनी मेमो, साइटेशन और स्रोत लिंक मिलते हैं",
    sourcesLabel: "स्रोत जिन पर शोध होता है",
    disclaimer:
      "यह अधिवक्ताओं की रिसर्च सहायता है, कानूनी सलाह नहीं। हर साइटेशन मूल निर्णय — Indian Kanoon, eSCR या SCI — पर जाकर वेरिफाई करें। अदालत में पेश करने से पहले वकील अपनी स्वतंत्र जाँच करें।",
    emptyHistory: "अभी कोई सेव मेमो नहीं। एक ब्रीफ चलाएँ, वो यहीं दिखेगा।",
    tabBrief: "मेमो",
    tabIssues: "मुद्दे",
    tabCases: "नज़ीरें",
    tabLaw: "कानून",
    tabArgs: "दलीलें",
    tabSources: "स्रोत",
    copyMemo: "मेमो कॉपी",
    copied: "कॉपी हो गया",
    print: "प्रिंट",
    save: "सेव",
    saved: "सेव हो गया",
    issues: "न्यायालय के मुद्दे",
    statutes: "लागू कानून",
    doctrines: "सिद्धांत",
    precedents: "मिलती नज़ीरें",
    points: "अदालत में तय हो सकने वाले बिंदु",
    forSide: "आपकी तरफ़ की दलीलें",
    against: "विरोधी दलीलें",
    counters: "जवाब / रिबटल",
    strategy: "रणनीति",
    risks: "जोखिम",
    unverified: "वेरिफाई करें — सर्च में मूल पाठ नहीं मिला",
    searched: "खोजे गए सवाल",
    errorTitle: "शोध पूरा नहीं हो सका",
    retry: "फिर कोशिश करें",
    back: "डेस्क पर वापस",
    backToMemo: "मेमो पर वापस",
    required: "तथ्य लिखें या दस्तावेज़ अपलोड करें — कम से कम एक पैराग्राफ।",
    aiDown: "इस समय AI रिसर्च उपलब्ध नहीं है। थोड़ी देर बाद कोशिश करें।",
    paywall: "आज़माइश खत्म। शोध जारी रखने के लिए चैंबर लें।",
    timeout: "स्रोत ढूँढ़ने में ज़्यादा समय लग गया। एक बार और चलाएँ — अक्सर दूसरी बार तेज़ होता है।",
    parseErr: "मेमो बन नहीं सका। तथ्य थोड़े साफ करके फिर कोशिश करें।",
    letterParseErr: "पत्र बन नहीं सका। मेमो से फिर कोशिश करें।",
    waitNote: "आमतौर पर 30–70 सेकंड।",
    cancel: "रद्द करें",
    wordBrief: "वर्ड",
    draftNotice: "सूचना",
    draftReply: "जवाब",
    draftPetition: "याचिका",
    draftWrittenStatement: "लिखित कथन",
    draftingLetter: "ड्राफ्ट हो रहा है…",
    letterWaitNote: "आमतौर पर 10–40 सेकंड।",
    copyLetter: "पत्र कॉपी",
    letterNoticeKicker: "कानूनी सूचना",
    letterReplyKicker: "सूचना का जवाब",
    letterPetitionKicker: "याचिका",
    letterWsKicker: "लिखित कथन",
    withoutPrejudice: "बिना पूर्वाग्रह के",
    letterParties: "पक्षकार",
    letterFacts: "तथ्य",
    letterGrounds: "कानूनी आधार",
    letterDemand: "माँग",
    letterTime: "पालन की अवधि",
    letterStand: "रुख",
    letterParaReply: "पैरावाइज़ जवाब",
    letterPrayer: "प्रार्थना",
    letterInterim: "अंतरिम राहत",
    letterVerification: "सत्यापन",
    letterPrelim: "प्रारंभिक आपत्तियाँ",
    letterCitation: "साइटेशन",
    letterUrl: "URL",
    files: "दस्तावेज़ अपलोड",
    filesHint: "FIR, आदेश, प्लीडिंग — PDF, फ़ोटो या टेक्स्ट। अधिकतम 3 फ़ाइलें, प्रत्येक लगभग 1 MB।",
    removeFile: "हटाएँ",
    deleteMemo: "मिटाएँ",
    signOut: "बाहर जाएँ",
    signingOut: "निकाल रहे हैं…",
    signIn: "लॉगिन",
    fileErr: "दस्तावेज़ पढ़ नहीं सके। PDF या टेक्स्ट आज़माएँ, या तथ्य लिख दें।",
    stageIssue: "तथ्यों से कानूनी मुद्दे निकाल रहे हैं",
    stageSearch: "Indian Kanoon, SCI, eSCR, LiveLaw पर खोज",
    stageRatio: "नज़ीर, रेशियो और सिद्धांत जोड़ रहे हैं",
    stageDraft: "अदालती मेमो ड्राफ्ट हो रहा है",
    binding: "बाध्यकारी",
    persuasive: "प्रेरक",
    distinguishable: "भिन्न करने योग्य",
    strong: "मज़बूत",
    moderate: "मध्यम",
    contested: "विवादित",
    sides: {
      petitioner: "याचिकाकर्ता / वादी",
      respondent: "प्रतिवादी / प्रत्यर्थी",
      neutral: "तटस्थ राय",
    } satisfies Record<Side, string>,
    areas: {
      constitutional: "संवैधानिक",
      criminal: "आपराधिक",
      civil: "दीवानी",
      family: "पारिवारिक",
      property: "संपत्ति / भूमि",
      service: "सेवा",
      labour: "श्रम",
      consumer: "उपभोक्ता",
      tax: "कर",
      arbitration: "मध्यस्थता",
      company: "कंपनी / दिवाला",
      ipr: "बौद्धिक संपदा",
      writ: "रिट",
      other: "अन्य",
    } satisfies Record<PracticeArea, string>,
  },
  en: {
    app: "CiteBench",
    tagline: "Practice assistant for Indian advocates · case-law research",
    hero: "Put in the facts. Pull the authorities.",
    kicker: "Supreme Court · High Courts · Indian statute",
    facts: "Facts of the case",
    factsHint:
      "Write what happened — parties, dates, documents, the dispute, and the relief sought. Hindi or English is fine.",
    query: "Specific legal question",
    queryHint: "e.g. Does anticipatory bail lie? Will a writ be maintainable?",
    court: "Court",
    area: "Practice area",
    side: "Side",
    memoLang: "Memo language",
    research: "Start research",
    researching: "Researching…",
    newBrief: "New brief",
    history: "Past memos",
    samples: "Sample briefs",
    how: "How it works",
    step1: "Enter facts or upload FIR/orders",
    step2: "CiteBench searches SCI, eSCR, Indian Kanoon, LiveLaw and CaseMine",
    step3: "Matching rulings are turned into issues, doctrines and submissions",
    step4: "You get a full legal memo with citations and source links",
    sourcesLabel: "Sources we search",
    disclaimer:
      "This is research assistance for advocates, not legal advice. Verify every citation against the original judgment on Indian Kanoon, eSCR or SCI. Independent professional review is required before filing.",
    emptyHistory: "No saved memos yet. Run a brief and it will appear here.",
    tabBrief: "Memo",
    tabIssues: "Issues",
    tabCases: "Precedents",
    tabLaw: "Law",
    tabArgs: "Arguments",
    tabSources: "Sources",
    copyMemo: "Copy memo",
    copied: "Copied",
    print: "Print",
    save: "Save",
    saved: "Saved",
    issues: "Issues for the court",
    statutes: "Applicable law",
    doctrines: "Doctrines",
    precedents: "Matching authorities",
    points: "Points the court may decide",
    forSide: "Submissions for your side",
    against: "Opposing submissions",
    counters: "Rebuttal",
    strategy: "Strategy",
    risks: "Risks",
    unverified: "Verify — original text was not retrieved in search",
    searched: "Queries searched",
    errorTitle: "Research could not finish",
    retry: "Try again",
    back: "Back to desk",
    backToMemo: "Back to memo",
    required: "Facts or a document are required — at least a short paragraph.",
    aiDown: "AI research is unavailable right now. Please try again shortly.",
    paywall: "Trial ended. Subscribe to keep researching.",
    timeout: "The source search ran long. Try once more — the second run is often faster.",
    parseErr: "The memo could not be assembled. Tighten the facts and retry.",
    letterParseErr: "The letter could not be assembled. Try again from the memo.",
    waitNote: "Usually 30–70s.",
    cancel: "Cancel",
    wordBrief: "Word",
    draftNotice: "Notice",
    draftReply: "Reply",
    draftPetition: "Petition",
    draftWrittenStatement: "Written statement",
    draftingLetter: "Drafting…",
    letterWaitNote: "Usually 10–40s.",
    copyLetter: "Copy letter",
    letterNoticeKicker: "legal notice",
    letterReplyKicker: "reply to notice",
    letterPetitionKicker: "petition",
    letterWsKicker: "written statement",
    withoutPrejudice: "Without prejudice",
    letterParties: "Parties",
    letterFacts: "Facts",
    letterGrounds: "Legal grounds",
    letterDemand: "Demand",
    letterTime: "Time to comply",
    letterStand: "Stand",
    letterParaReply: "Para-wise reply",
    letterPrayer: "Prayer",
    letterInterim: "Interim relief",
    letterVerification: "Verification",
    letterPrelim: "Preliminary objections",
    letterCitation: "Citation",
    letterUrl: "URL",
    files: "Upload documents",
    filesHint: "FIR, orders, pleadings — PDF, photo or text. Up to 3 files, about 1 MB each.",
    removeFile: "Remove",
    deleteMemo: "Delete",
    signOut: "Sign out",
    signingOut: "Signing out…",
    signIn: "Sign in",
    fileErr: "Could not read the files. Try PDF or text, or paste the facts.",
    stageIssue: "Framing issues from the facts",
    stageSearch: "Searching Indian Kanoon, SCI, eSCR, LiveLaw",
    stageRatio: "Matching ratio, doctrines and holdings",
    stageDraft: "Drafting the court-ready memo",
    binding: "Binding",
    persuasive: "Persuasive",
    distinguishable: "Distinguishable",
    strong: "Strong",
    moderate: "Moderate",
    contested: "Contested",
    sides: {
      petitioner: "Petitioner / Plaintiff",
      respondent: "Respondent / Defendant",
      neutral: "Neutral opinion",
    } satisfies Record<Side, string>,
    areas: {
      constitutional: "Constitutional",
      criminal: "Criminal",
      civil: "Civil",
      family: "Family",
      property: "Property / land",
      service: "Service",
      labour: "Labour",
      consumer: "Consumer",
      tax: "Tax",
      arbitration: "Arbitration",
      company: "Company / IBC",
      ipr: "Intellectual property",
      writ: "Writ",
      other: "Other",
    } satisfies Record<PracticeArea, string>,
  },
} as const;

export type Copy = (typeof copy)[OutputLang];

export function t(lang: OutputLang): Copy {
  return copy[lang];
}
