import type { OutputLang } from "@/lib/research/types";

export const billingCopy = {
  hi: {
    plan: "प्लान",
    kicker: "CiteBench चैंबर",
    title: "30 दिन आज़माइश, फिर चैंबर।",
    lead: "नमूना चैंबर मुफ़्त है — घड़ी नहीं चलती। 30 दिन तब शुरू होंगे जब आप अपना मामला शोध करें। कार्ड नहीं। बाद में ₹500 / महीना।",
    trialOn: "आज़माइश चल रही है",
    trialDays: "दिन बाकी",
    trialIdle: "शुरू नहीं हुई — नमूना चैंबर मुफ़्त है",
    trialEnded: "आज़माइश खत्म। शोध और AI के लिए चैंबर लें।",
    paidOn: "चैंबर चालू है",
    accessUntil: "पहुँच कब तक",
    cancelledOn: "रद्द — अवधि तक पहुँच रहेगी",
    expired: "अवधि समाप्त",
    price: "₹500",
    perMonth: "/ महीना",
    gst: "GST अलग। मासिक, जब तक रद्द न करें।",
    includes: "इसमें क्या है",
    itemResearch: "भारतीय केस-लॉ शोध डेस्क",
    itemChamber: "डायरी, मामले, पेशियाँ, समय-सीमा",
    itemOrders: "आदेश पढ़ना और पेशी ब्रीफ",
    itemTrial: "अपने मामलों पर 30 दिन मुफ़्त — नमूना चैंबर नहीं गिना जाता",
    subscribe: "चैंबर शुरू करें — ₹500 / महीना",
    subscribing: "खोल रहे हैं…",
    subscribed: "चैंबर खुल गया।",
    cancelPlan: "सदस्यता रद्द करें",
    cancelled: "रद्द हो गई। अवधि तक डेस्क चलेगा।",
    paywall: "आज़माइश खत्म। शोध जारी रखने के लिए चैंबर लें।",
    seePlan: "प्लान देखें",
    noCard: "कार्ड अभी नहीं चाहिए।",
    confirmHint:
      "यह पूर्वावलोकन सदस्यता आपके अकाउंट पर दर्ज करता है। लाइव भुगतान जुड़ने पर यहीं कार्ड कटेगा।",
    bannerTrial: "आज़माइश",
    bannerIdle: "नमूना मुफ़्त · आज़माइश बाकी",
    bannerExpired: "आज़माइश खत्म — चैंबर लें",
    bannerLeft: "दिन बाकी",
  },
  en: {
    plan: "Plan",
    kicker: "CiteBench chamber",
    title: "30 days free, then the chamber.",
    lead: "Sample chamber is free and does not start the clock. The 30 days begin when you research your own matter. No card. Then ₹500 a month.",
    trialOn: "Trial running",
    trialDays: "days left",
    trialIdle: "Not started — sample chamber is free",
    trialEnded: "Trial ended. Subscribe to keep researching.",
    paidOn: "Chamber is on",
    accessUntil: "Access until",
    cancelledOn: "Cancelled — access until the period ends",
    expired: "Ended",
    price: "₹500",
    perMonth: "/ month",
    gst: "GST extra. Monthly, until you cancel.",
    includes: "What you get",
    itemResearch: "Indian case-law research desk",
    itemChamber: "Diary, matters, hearings, deadlines",
    itemOrders: "Order reading and hearing briefs",
    itemTrial: "30-day free trial on your own matters — sample does not count",
    subscribe: "Start chamber — ₹500 / month",
    subscribing: "Opening…",
    subscribed: "Chamber is open.",
    cancelPlan: "Cancel subscription",
    cancelled: "Cancelled. The desk stays open until the period ends.",
    paywall: "Trial ended. Subscribe to keep researching.",
    seePlan: "See the plan",
    noCard: "No card needed to start.",
    confirmHint:
      "This preview records the subscription on your account. When live payments are connected, this is where the card will be charged.",
    bannerTrial: "Trial",
    bannerIdle: "Sample is free · trial unused",
    bannerExpired: "Trial ended — open the chamber",
    bannerLeft: "days left",
  },
} as const;

export function b(lang: OutputLang) {
  return billingCopy[lang];
}
