import type { OutputLang } from "@/lib/research/types";

export const billingCopy = {
  hi: {
    plan: "प्लान",
    kicker: "CiteBench चैंबर",
    title: "30 दिन आज़माइश, फिर चैंबर।",
    lead: "नमूना चैंबर मुफ़्त है — घड़ी नहीं चलती। 30 दिन तब शुरू होंगे जब आप अपना मामला शोध करें। कार्ड नहीं। बाद में ₹500 / महीना।",
    leadLive:
      "नमूना चैंबर मुफ़्त है — घड़ी नहीं चलती। 30 दिन तब शुरू होंगे जब आप अपना मामला शोध करें। फिर ₹500 / महीना, UPI, कार्ड या नेटबैंकिंग से।",
    trialOn: "आज़माइश चल रही है",
    trialDays: "दिन बाकी",
    trialIdle: "शुरू नहीं हुई — नमूना चैंबर मुफ़्त है",
    trialEnded: "आज़माइश खत्म। शोध और AI के लिए चैंबर लें।",
    paidOn: "चैंबर चालू है",
    accessUntil: "पहुँच कब तक",
    cancelledOn: "रद्द — अवधि तक पहुँच रहेगी",
    expired: "अवधि समाप्त",
    price: "₹500",
    perMonth: "/ महीना",
    gst: "₹500 पूरा। एक भुगतान 30 दिन का है।",
    includes: "इसमें क्या है",
    itemResearch: "भारतीय केस-लॉ शोध डेस्क",
    itemChamber: "डायरी, मामले, पेशियाँ, समय-सीमा",
    itemOrders: "आदेश पढ़ना और पेशी ब्रीफ",
    itemTrial: "अपने मामलों पर 30 दिन मुफ़्त — नमूना चैंबर नहीं गिना जाता",
    subscribe: "चैंबर शुरू करें — ₹500 / महीना",
    subscribing: "खोल रहे हैं…",
    subscribed: "चैंबर खुल गया।",
    cancelPlan: "सदस्यता रद्द करें",
    cancelled: "रद्द हो गई। अवधि तक डेस्क चलेगा।",
    paywall: "आज़माइश खत्म। शोध जारी रखने के लिए चैंबर लें।",
    seePlan: "प्लान देखें",
    noCard: "कार्ड अभी नहीं चाहिए।",
    confirmHint:
      "यह पूर्वावलोकन सदस्यता आपके अकाउंट पर दर्ज करता है। लाइव भुगतान जुड़ने पर यहीं कार्ड कटेगा।",
    confirmHintLive:
      "UPI, कार्ड या नेटबैंकिंग। चैंबर भुगतान सफल होने के बाद खुलता है। एक भुगतान 30 दिन का है।",
    paymentsUnset: "भुगतान अभी जुड़ा नहीं है। तब तक पैसे नहीं कटेंगे।",
    checkoutDismissed: "भुगतान रद्द। चैंबर नहीं खुला।",
    leftoverHint: "डेस्क इस तारीख तक खुला रहेगा। उसके बाद सब्सक्राइब करने पर भुगतान शुरू होगा।",
    payFailed: "भुगतान नहीं खुल सका।",
    account: "अकाउंट",
    deleteAccount: "मेरा अकाउंट हटाएँ",
    deleteAccountHint:
      "मामले, मेमो, प्लान और लॉगिन मिट जाएँगे। उसी ईमेल से फिर रजिस्टर कर सकते हैं।",
    deleteAccountConfirm:
      "अकाउंट हटाना नहीं आ सकता। सभी मामले और मेमो खत्म। जारी रखें?",
    deletingAccount: "हटा रहे हैं…",
    deletedAccount: "अकाउंट हट गया।",
    deleteFailed: "अकाउंऒ हटा नहीं सका।",
    bannerTrial: "आज़माइश",
    bannerIdle: "नमूना मुफ़्त · आज़माइश बाकी",
    bannerExpired: "आज़माइश खत्म — चैंबर लें",
    bannerLeft: "दिन बाकी",
  },
  en: {
    plan: "Plan",
    kicker: "CiteBench chamber",
    title: "30 days free, then the chamber.",
    lead: "Sample chamber is free and does not start the clock. The 30 days begin when you research your own matter. No card. Then ₹500 a month.",
    leadLive:
      "Sample chamber is free and does not start the clock. The 30 days begin when you research your own matter. Then ₹500 a month, paid with UPI, card, or netbanking.",
    trialOn: "Trial running",
    trialDays: "days left",
    trialIdle: "Not started — sample chamber is free",
    trialEnded: "Trial ended. Subscribe to keep researching.",
    paidOn: "Chamber is on",
    accessUntil: "Access until",
    cancelledOn: "Cancelled — access until the period ends",
    expired: "Ended",
    price: "₹500",
    perMonth: "/ month",
    gst: "₹500 is the price. Each payment covers 30 days.",
    includes: "What you get",
    itemResearch: "Indian case-law research desk",
    itemChamber: "Diary, matters, hearings, deadlines",
    itemOrders: "Order reading and hearing briefs",
    itemTrial: "30-day free trial on your own matters — sample does not count",
    subscribe: "Start chamber — ₹500 / month",
    subscribing: "Opening…",
    subscribed: "Chamber is open.",
    cancelPlan: "Cancel subscription",
    cancelled: "Cancelled. The desk stays open until the period ends.",
    paywall: "Trial ended. Subscribe to keep researching.",
    seePlan: "See the plan",
    noCard: "No card needed to start.",
    confirmHint:
      "This preview records the subscription on your account. When live payments are connected, this is where the card will be charged.",
    confirmHintLive:
      "UPI, card, or netbanking. The chamber opens after payment succeeds. Each payment covers 30 days.",
    paymentsUnset: "Payments are not connected yet. The chamber cannot take money until they are.",
    checkoutDismissed: "Payment cancelled. The chamber did not open.",
    leftoverHint: "The desk stays open until this date. Payment starts the next time you subscribe after it ends.",
    payFailed: "Could not open payment.",
    account: "Account",
    deleteAccount: "Delete my account",
    deleteAccountHint:
      "Matters, memos, plan, and login are removed. You can register again with the same email.",
    deleteAccountConfirm:
      "This cannot be undone. Every matter and memo will be deleted. Continue?",
    deletingAccount: "Deleting…",
    deletedAccount: "Account deleted.",
    deleteFailed: "Could not delete the account.",
    bannerTrial: "Trial",
    bannerIdle: "Sample is free · trial unused",
    bannerExpired: "Trial ended — open the chamber",
    bannerLeft: "days left",
  },
} as const;

export function b(lang: OutputLang) {
  return billingCopy[lang];
}
