// @ts-nocheck
import type { OutputLang } from "@/lib/research/types";
import type { Origin } from "./types";

export const appCopy = {
	hi: {
		app: "CiteBench",
		tagline: "अधिवक्ता का प्रैक्टिस असिस्टेंट",
		kicker: "आज · डायरी · मामला · शोध",
		hero: "आज क्या करना है।",
		today: "आज",
		diary: "डायरी",
		matters: "मामले",
		research: "शोध",
		inbox: "इनबॉक्स",
		signInNeed: "चैंबर खोलने के लिए लॉगिन करें। 30 दिन आज़माइश, कार्ड नहीं।",
		loadSample: "नमूना चैंबर खोलें",
		sampleLoaded: "तीन नमूना मामले आ गए।",
		clearSample: "नमूना चैंबर बंद करें",
		clearSampleHint: "तीन डेमो मामले हटाकर खाली डेस्क पर लौटें।",
		clearSampleConfirm: "नमूना चैंबर हटाएँ? तीन डेमो मामले मिट जाएँगे।",
		clearSampleYes: "डेमो हटाएँ",
		clearSampleNo: "रहने दें",
		clearedSample: "नमूना चैंबर हट गया।",
		sampleErr: "नमूना चैंबर बदल नहीं सका।",
		sampleBanner: "यह नमूना चैंबर है। मुफ़्त है — आज़माइश नहीं चलती।",
		reloadSample: "पूरे तथ्य फिर से लोड करें",
		reloadedSample: "नमूना चैंबर पूरे केस-फ़ाइल के साथ अपडेट हो गया।",
		newMatter: "नया मामला",
		saveMatter: "मामला सहेजें",
		hearingsToday: "आज की पेशियाँ",
		upcoming: "आने वाली पेशियाँ",
		deadlines: "समय-सीमा",
		tasks: "कार्य",
		ordersAction: "आदेश — पुष्टि बाकी",
		stale: "ध्यान वाले मामले",
		emptyToday: "आज कोई पेशी या समय-सीमा नहीं। मामला बनाएँ, या नमूना चैंबर खोलें।",
		emptyMatters: "अभी कोई मामला नहीं।",
		emptyDiary: "कोई पेशी डायरी में नहीं।",
		emptyInbox: "कोई आदेश पुष्टि के लिए नहीं। नीचे टेक्स्ट चिपकाएँ।",
		courtName: "अदालत",
		caseNo: "केस नंबर",
		cnr: "CNR",
		stage: "चरण",
		proceeding: "कार्यवाही",
		parties: "पक्षकार",
		client: "क्लाइंट",
		ourSide: "हमारा पक्ष",
		notes: "नोट",
		nextHearing: "अगली पेशी",
		lastOrder: "पिछला आदेश",
		addHearing: "पेशी जोड़ें",
		recordHearing: "पेशी दर्ज करें",
		date: "तारीख",
		time: "समय",
		purpose: "उद्देश्य",
		courtroom: "कमरा / बेंच",
		outcome: "क्या हुआ",
		whatCourtSaid: "अदालत ने क्या कहा",
		nextDate: "अगली तारीख",
		pasteOrder: "आदेश चिपकाएँ",
		analyseOrder: "आदेश पढ़ें",
		analysing: "पढ़ रहे हैं…",
		confirm: "पुष्टि करें — चैंबर अपडेट हो",
		reject: "हटाएँ",
		courtDirected: "अदालत का निर्देश",
		aiSuggestion: "CiteBench सुझाव",
		prepareBrief: "पेशी ब्रीफ",
		briefing: "ब्रीफ बन रहा है…",
		markDone: "हो गया",
		dismiss: "नहीं",
		possibleNext: "आगे क्या हो सकता है",
		typicalDocs: "आमतौर पर दस्तावेज़",
		typicalDeadlines: "आमतौर पर समय-सीमा",
		lawyerDoes: "वकील क्या करता है",
		courtDoes: "अदालत क्या करती है",
		humanGate: "वकील तय करेगा",
		aiCan: "AI मदद कर सकता है",
		trustNote: "अदालत का निर्देश और CiteBench का सुझाव अलग रखे जाते हैं। सुझाव अपने आप निर्देश नहीं बनते।",
		disclaimer: "CiteBench प्रैक्टिस सहायता है, कानूनी सलाह नहीं। तारीखें, निर्देश और साइटेशन फाइल करने से पहले स्वयं जाँचें।",
		modelNote: "कार्यवाही एक चेकलिस्ट नहीं — शाखाओं वाला वर्कफ़्लो है।",
		attachResearch: "इस मामले से शोध",
		inboxHint: "आदेश या नोटिस का पाठ चिपकाएँ। AI निर्देश निकालेगा; आप पुष्टि करेंगे।",
		noMatter: "पहले एक मामला चुनें।",
		originLawyer: "वकील",
		originCourt: "अदालत",
		originAi: "AI",
		originStatute: "कानून",
		originSystem: "सिस्टम",
		statusActive: "चल रहा",
		statusStayed: "स्थगित",
		statusDormant: "सुप्त",
		statusClosed: "बंद",
		openTasks: "खुले कार्य",
		timeline: "टाइमलाइन",
		documents: "दस्तावेज़",
		orders: "आदेश",
		addTask: "कार्य जोड़ें",
		taskTitle: "कार्य",
		due: "नियत",
		created: "बना",
		untitled: "बिना शीर्षक",
		requiredTitle: "मामले का शीर्षक लिखें।",
		listedAt: "बोर्ड समय",
		sampleHint: "शर्मा बनाम एपेक्स (वाणिज्यिक वसूली), राज्य बनाम राकेश (नियमित ज़मानत), मेहता रिट (अतिथि व्याख्याता) — आदेश, FIR और समय-सीमा सहित।",
		hearingBrief: "पेशी ब्रीफ",
		caveats: "सावधानियाँ",
		extractSummary: "सार",
		extractedDirections: "निकाले गए निर्देश",
		suggestedTasks: "सुझाए कार्य",
		stageHint: "संभावित चरण",
		confirmStage: "चरण बदलें",
		keepStage: "चरण न बदलें",
		signOut: "बाहर जाएँ",
		signIn: "लॉगिन",
		signingOut: "निकाल रहे हैं…",
		back: "वापस",
		save: "सहेजें",
		cancel: "रद्द",
		openLinked: "जुड़ा रिकॉर्ड खोलें",
		emptyDocs: "इस फ़ाइल पर अभी कोई दस्तावेज़ नहीं।",
		emptyOrders: "इस फ़ाइल पर अभी कोई आदेश नहीं।",
		emptyHearings: "कोई पेशी सूचीबद्ध नहीं।",
		jumpNotes: "नोट",
		paywall: "आज़माइश खत्म। शोध जारी रखने के लिए चैंबर लें।",
		caseType: "केस प्रकार",
		jurisdiction: "क्षेत्राधिकार",
		partiesHint: "एक पंक्ति में एक पक्ष — भूमिका, नाम",
		whatHappens: "कानूनी तौर पर क्या हो रहा है",
		failedAi: "AI इस समय उपलब्ध नहीं। पाठ स्वयं दर्ज करें।",
		parseErr: "निकाल नहीं सके। आदेश साफ करके फिर कोशिश करें।"
	},
	en: {
		app: "CiteBench",
		tagline: "The lawyer's practice assistant",
		kicker: "Today · diary · matter · research",
		hero: "What needs you today.",
		today: "Today",
		diary: "Diary",
		matters: "Matters",
		research: "Research",
		inbox: "Inbox",
		signInNeed: "Sign in to open the chamber. 30-day trial, no card.",
		loadSample: "Load a sample chamber",
		sampleLoaded: "Three sample matters are on the desk.",
		clearSample: "Exit sample chamber",
		clearSampleHint: "Remove the three demo matters and start from an empty desk.",
		clearSampleConfirm: "Exit the sample chamber? The three demo matters will be removed.",
		clearSampleYes: "Remove demo",
		clearSampleNo: "Keep sample",
		clearedSample: "Sample chamber cleared.",
		sampleErr: "Could not change the sample chamber.",
		sampleBanner: "You are in the sample chamber. It is free and does not start the trial.",
		reloadSample: "Reload full sample facts",
		reloadedSample: "Sample chamber updated with the full case files.",
		newMatter: "New matter",
		saveMatter: "Save matter",
		hearingsToday: "Hearings today",
		upcoming: "Coming up",
		deadlines: "Deadlines",
		tasks: "Tasks",
		ordersAction: "Orders to confirm",
		stale: "Needs attention",
		emptyToday: "Nothing listed today. File a matter, or load the sample chamber.",
		emptyMatters: "No matters yet.",
		emptyDiary: "No hearings in the diary.",
		emptyInbox: "Nothing waiting to confirm. Paste an order below.",
		courtName: "Court",
		caseNo: "Case number",
		cnr: "CNR",
		stage: "Stage",
		proceeding: "Proceeding",
		parties: "Parties",
		client: "Client",
		ourSide: "Our side",
		notes: "Notes",
		nextHearing: "Next hearing",
		lastOrder: "Last order",
		addHearing: "Add hearing",
		recordHearing: "Record hearing",
		date: "Date",
		time: "Time",
		purpose: "Purpose",
		courtroom: "Room / bench",
		outcome: "What happened",
		whatCourtSaid: "What the court said",
		nextDate: "Next date",
		pasteOrder: "Paste order",
		analyseOrder: "Read the order",
		analysing: "Reading…",
		confirm: "Confirm — update the chamber",
		reject: "Discard",
		courtDirected: "Court direction",
		aiSuggestion: "CiteBench suggestion",
		prepareBrief: "Hearing brief",
		briefing: "Preparing brief…",
		markDone: "Done",
		dismiss: "Dismiss",
		possibleNext: "What can happen next",
		typicalDocs: "Usual documents",
		typicalDeadlines: "Usual deadlines",
		lawyerDoes: "What the lawyer does",
		courtDoes: "What the court does",
		humanGate: "Lawyer decides",
		aiCan: "AI can assist",
		trustNote: "Court directions and CiteBench suggestions stay distinct. A suggestion never becomes a direction on its own.",
		disclaimer: "CiteBench is practice assistance, not legal advice. Verify dates, directions and citations before you file or appear.",
		modelNote: "A proceeding is a branching workflow, not a checklist.",
		attachResearch: "Research this matter",
		inboxHint: "Paste an order or notice. The model extracts; you confirm.",
		noMatter: "Pick a matter first.",
		originLawyer: "Lawyer",
		originCourt: "Court",
		originAi: "AI",
		originStatute: "Statute",
		originSystem: "System",
		statusActive: "Active",
		statusStayed: "Stayed",
		statusDormant: "Dormant",
		statusClosed: "Closed",
		openTasks: "Open tasks",
		timeline: "Timeline",
		documents: "Documents",
		orders: "Orders",
		addTask: "Add task",
		taskTitle: "Task",
		due: "Due",
		created: "Created",
		untitled: "Untitled",
		requiredTitle: "A matter needs a title.",
		listedAt: "Board time",
		sampleHint: "Sharma v Apex (commercial recovery), State v Rakesh (regular bail), Mehta writ (guest faculty) — with orders, FIR and clocks.",
		hearingBrief: "Hearing brief",
		caveats: "Caveats",
		extractSummary: "Summary",
		extractedDirections: "Extracted directions",
		suggestedTasks: "Suggested tasks",
		stageHint: "Possible stage",
		confirmStage: "Move stage",
		keepStage: "Keep stage",
		signOut: "Sign out",
		signIn: "Sign in",
		signingOut: "Signing out…",
		back: "Back",
		save: "Save",
		cancel: "Cancel",
		openLinked: "Open linked record",
		emptyDocs: "No papers on this file yet.",
		emptyOrders: "No orders on this file yet.",
		emptyHearings: "No hearings listed.",
		jumpNotes: "Notes",
		paywall: "Trial ended. Subscribe to keep researching.",
		caseType: "Case type",
		jurisdiction: "Jurisdiction",
		partiesHint: "One party per line — role, name",
		whatHappens: "What is happening legally",
		failedAi: "AI is unavailable. Record it yourself.",
		parseErr: "Could not extract. Clean the order text and retry."
	}
};
export function p(lang: OutputLang) {
	return appCopy[lang];
}
export function originLabel(lang: OutputLang, origin: Origin) {
	const c = p(lang);
	if (origin === "court_direction") return c.originCourt;
	if (origin === "statute") return c.originStatute;
	if (origin === "ai_inference" || origin === "ai_suggestion") return c.originAi;
	if (origin === "system") return c.originSystem;
	return c.originLawyer;
}
