/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as DiaryRouteImport } from './routes/diary'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MattersRouteImport } from './routes/matters'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as StoryRouteImport } from './routes/story'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as ApiCreateOrderRouteImport } from './routes/api/create-order'
import { Route as ApiVerifyPaymentRouteImport } from './routes/api/verify-payment'
import { Route as MattersIndexRouteImport } from './routes/matters.index'
import { Route as MattersIdRouteImport } from './routes/matters.$id'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminUsersIdRouteImport } from './routes/admin.users.$id'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiBillingRazorpayRouteImport } from './routes/api/billing.razorpay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaryRoute = DiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MattersRoute = MattersRouteImport.update({
  id: '/matters',
  path: '/matters',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const StoryRoute = StoryRouteImport.update({
  id: '/story',
  path: '/story',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const ApiCreateOrderRoute = ApiCreateOrderRouteImport.update({
  id: '/api/create-order',
  path: '/api/create-order',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVerifyPaymentRoute = ApiVerifyPaymentRouteImport.update({
  id: '/api/verify-payment',
  path: '/api/verify-payment',
  getParentRoute: () => rootRouteImport,
} as any)
const MattersIndexRoute = MattersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MattersRoute,
} as any)
const MattersIdRoute = MattersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MattersRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminUsersRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingRazorpayRoute = ApiBillingRazorpayRouteImport.update({
  id: '/api/billing/razorpay',
  path: '/api/billing/razorpay',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/billing': typeof BillingRoute
  '/diary': typeof DiaryRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/matters': typeof MattersRouteWithChildren
  '/research': typeof ResearchRoute
  '/story': typeof StoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/api/create-order': typeof ApiCreateOrderRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
  '/matters/$id': typeof MattersIdRoute
  '/admin/': typeof AdminIndexRoute
  '/matters/': typeof MattersIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/razorpay': typeof ApiBillingRazorpayRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/diary': typeof DiaryRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/research': typeof ResearchRoute
  '/story': typeof StoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/create-order': typeof ApiCreateOrderRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
  '/matters/$id': typeof MattersIdRoute
  '/admin': typeof AdminIndexRoute
  '/matters': typeof MattersIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/razorpay': typeof ApiBillingRazorpayRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/billing': typeof BillingRoute
  '/diary': typeof DiaryRoute
  '/inbox': typeof InboxRoute
  '/login': typeof LoginRoute
  '/matters': typeof MattersRouteWithChildren
  '/research': typeof ResearchRoute
  '/story': typeof StoryRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/api/create-order': typeof ApiCreateOrderRoute
  '/api/verify-payment': typeof ApiVerifyPaymentRoute
  '/matters/$id': typeof MattersIdRoute
  '/admin/': typeof AdminIndexRoute
  '/matters/': typeof MattersIndexRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/billing/razorpay': typeof ApiBillingRazorpayRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/billing'
    | '/diary'
    | '/inbox'
    | '/login'
    | '/matters'
    | '/research'
    | '/story'
    | '/admin/login'
    | '/admin/users'
    | '/api/create-order'
    | '/api/verify-payment'
    | '/matters/$id'
    | '/admin/'
    | '/matters/'
    | '/admin/users/$id'
    | '/api/auth/$'
    | '/api/billing/razorpay'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/diary'
    | '/inbox'
    | '/login'
    | '/research'
    | '/story'
    | '/admin/login'
    | '/api/create-order'
    | '/api/verify-payment'
    | '/matters/$id'
    | '/admin'
    | '/matters'
    | '/admin/users/$id'
    | '/api/auth/$'
    | '/api/billing/razorpay'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/billing'
    | '/diary'
    | '/inbox'
    | '/login'
    | '/matters'
    | '/research'
    | '/story'
    | '/admin/login'
    | '/admin/users'
    | '/api/create-order'
    | '/api/verify-payment'
    | '/matters/$id'
    | '/admin/'
    | '/matters/'
    | '/admin/users/$id'
    | '/api/auth/$'
    | '/api/billing/razorpay'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BillingRoute: typeof BillingRoute
  DiaryRoute: typeof DiaryRoute
  InboxRoute: typeof InboxRoute
  LoginRoute: typeof LoginRoute
  MattersRoute: typeof MattersRouteWithChildren
  ResearchRoute: typeof ResearchRoute
  StoryRoute: typeof StoryRoute
  ApiCreateOrderRoute: typeof ApiCreateOrderRoute
  ApiVerifyPaymentRoute: typeof ApiVerifyPaymentRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiBillingRazorpayRoute: typeof ApiBillingRazorpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diary': {
      id: '/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof DiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matters': {
      id: '/matters'
      path: '/matters'
      fullPath: '/matters'
      preLoaderRoute: typeof MattersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/story': {
      id: '/story'
      path: '/story'
      fullPath: '/story'
      preLoaderRoute: typeof StoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/create-order': {
      id: '/api/create-order'
      path: '/api/create-order'
      fullPath: '/api/create-order'
      preLoaderRoute: typeof ApiCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/verify-payment': {
      id: '/api/verify-payment'
      path: '/api/verify-payment'
      fullPath: '/api/verify-payment'
      preLoaderRoute: typeof ApiVerifyPaymentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matters/': {
      id: '/matters/'
      path: '/'
      fullPath: '/matters/'
      preLoaderRoute: typeof MattersIndexRouteImport
      parentRoute: typeof MattersRoute
    }
    '/matters/$id': {
      id: '/matters/$id'
      path: '/$id'
      fullPath: '/matters/$id'
      preLoaderRoute: typeof MattersIdRouteImport
      parentRoute: typeof MattersRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/razorpay': {
      id: '/api/billing/razorpay'
      path: '/api/billing/razorpay'
      fullPath: '/api/billing/razorpay'
      preLoaderRoute: typeof ApiBillingRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminUsersRouteChildren {
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersIdRoute: AdminUsersIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MattersRouteChildren {
  MattersIdRoute: typeof MattersIdRoute
  MattersIndexRoute: typeof MattersIndexRoute
}

const MattersRouteChildren: MattersRouteChildren = {
  MattersIdRoute: MattersIdRoute,
  MattersIndexRoute: MattersIndexRoute,
}

const MattersRouteWithChildren =
  MattersRoute._addFileChildren(MattersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BillingRoute: BillingRoute,
  DiaryRoute: DiaryRoute,
  InboxRoute: InboxRoute,
  LoginRoute: LoginRoute,
  MattersRoute: MattersRouteWithChildren,
  ResearchRoute: ResearchRoute,
  StoryRoute: StoryRoute,
  ApiCreateOrderRoute: ApiCreateOrderRoute,
  ApiVerifyPaymentRoute: ApiVerifyPaymentRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiBillingRazorpayRoute: ApiBillingRazorpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
